#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://dnlaptopstore.mariadb.database.azure.com/laptop_store
#    username: ls_admin@dnlaptopstore
#    password: LaptopStore1
#  jpa:
#    show-sql: true
#  cache:
#    type: redis
#  redis:
#    host: dnlaptopstore.redis.cache.windows.net
#    port: 6380
#    password: 55cQ3S8zsGqjcFltm9jRtzJxpNWsXbBHtfQ4u5oN0Zw=
#    ssl: true
#
#security:
#  jwt:
#    token:
#      secret-key: LAPTOP_STORE
#      access-token-expire-length: 900000        #15 minutes
#      refresh-token-expire-length: 2592000000   # 30 days
#
#server:
#  error:
#    include-message: always
#    include-binding-errors: always

# --- LOCAL DEVELOPMENT ---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/laptop_store?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6380
  mail:
    host: smtp.gmail.com
    username: nhidh99@gmail.com
    password: g89H*(hHWOIGH983GHJKSLH
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    test-connection: false
    default-encoding: UTF-8
  jackson:
    property-naming-strategy: SNAKE_CASE

security:
  jwt:
    token:
      secret-key: MGKADq5OZk@xRqEr4c8lF!1cJ6rTiSOP
  facebook:
    app-uri: https://graph.facebook.com
    app-id: 523568205328673
    app-secret: 80b7dd68ee19516217148e7fd2372a85
    app-token: 523568205328673|F9mlM5V_exus5CWJhkOwYDAK7ng

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080



# --- DOCKER DEVELOPMENT ---
#
#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://mariadb:3306/laptop_store
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#  cache:
#    type: redis
#  redis:
#    host: redis
#    port: 6379
#
#security:
#  jwt:
#    token:
#      secret-key: LAPTOP_STORE
#      access-token-expire-length: 900000        #15 minutes
#      refresh-token-expire-length: 2592000000   # 30 days
#
#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#  port: 8081